/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Accounts: () => import('#controllers/accounts_controller'),
  Checkins: () => import('#controllers/checkins_controller'),
  Notifications: () => import('#controllers/notifications_controller'),
  Overview: () => import('#controllers/overview_controller'),
  Projects: () => import('#controllers/projects_controller'),
  ServiceNodes: () => import('#controllers/service_nodes_controller'),
}
