/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSnapshotSchema extends BaseModel {
  static $columns = ['activeProjects', 'availableBalance', 'canCheckin', 'id', 'managedAccountId', 'payload', 'recharge', 'todayProfit', 'totalAssets', 'totalProfit', 'updatedAt', 'yesterdayProfit'] as const
  $columns = AccountSnapshotSchema.$columns
  @column()
  declare activeProjects: number
  @column()
  declare availableBalance: string
  @column()
  declare canCheckin: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare managedAccountId: number
  @column()
  declare payload: any
  @column()
  declare recharge: string
  @column()
  declare todayProfit: string
  @column()
  declare totalAssets: string
  @column()
  declare totalProfit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare yesterdayProfit: string
}

export class CheckinSnapshotSchema extends BaseModel {
  static $columns = ['calendar', 'canCheckin', 'continueDays', 'currentDay', 'id', 'managedAccountId', 'payload', 'rewards', 'todayFlag', 'totalRevenue', 'updatedAt'] as const
  $columns = CheckinSnapshotSchema.$columns
  @column()
  declare calendar: any
  @column()
  declare canCheckin: boolean
  @column()
  declare continueDays: number
  @column()
  declare currentDay: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare managedAccountId: number
  @column()
  declare payload: any
  @column()
  declare rewards: any
  @column()
  declare todayFlag: number | null
  @column()
  declare totalRevenue: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class HmcAccountSchema extends BaseModel {
  static $columns = ['account', 'createdAt', 'lastError', 'lastSyncAt', 'password', 'token', 'updatedAt'] as const
  $columns = HmcAccountSchema.$columns
  @column({ isPrimary: true })
  declare account: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lastSyncAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class HmcNotificationSchema extends BaseModel {
  static $columns = ['account', 'category', 'createdAt', 'id', 'level', 'message'] as const
  $columns = HmcNotificationSchema.$columns
  @column()
  declare account: string | null
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare level: string
  @column()
  declare message: string
}

export class ManagedAccountSchema extends BaseModel {
  static $columns = ['account', 'containerCode', 'createdAt', 'id', 'lastError', 'lastSyncedAt', 'password', 'slug', 'status', 'token', 'tokenExpiresAt', 'tokenStatus', 'updatedAt'] as const
  $columns = ManagedAccountSchema.$columns
  @column()
  declare account: string
  @column()
  declare containerCode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare token: string
  @column()
  declare tokenExpiresAt: number | null
  @column()
  declare tokenStatus: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['accountSlug', 'createdAt', 'id', 'level', 'message', 'meta', 'scope', 'title'] as const
  $columns = NotificationSchema.$columns
  @column()
  declare accountSlug: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare level: string
  @column()
  declare message: string
  @column()
  declare meta: any
  @column()
  declare scope: string
  @column()
  declare title: string
}

export class ProjectSnapshotSchema extends BaseModel {
  static $columns = ['dailyProfit', 'descriptionHtml', 'endTime', 'extraFlag', 'iconUrl', 'id', 'isReceive', 'managedAccountId', 'orderNo', 'payAmount', 'payload', 'periodDays', 'projectName', 'receiveTime', 'remoteOrderId', 'runStatus', 'totalIncome', 'totalRevenue', 'updatedAt'] as const
  $columns = ProjectSnapshotSchema.$columns
  @column()
  declare dailyProfit: string
  @column()
  declare descriptionHtml: string | null
  @column()
  declare endTime: number
  @column()
  declare extraFlag: number
  @column()
  declare iconUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isReceive: boolean
  @column()
  declare managedAccountId: number
  @column()
  declare orderNo: string | null
  @column()
  declare payAmount: string
  @column()
  declare payload: any
  @column()
  declare periodDays: number
  @column()
  declare projectName: string
  @column()
  declare receiveTime: number | null
  @column()
  declare remoteOrderId: number
  @column()
  declare runStatus: number
  @column()
  declare totalIncome: string
  @column()
  declare totalRevenue: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ServiceNodeSchema extends BaseModel {
  static $columns = ['allocationOrder', 'baseUrl', 'code', 'createdAt', 'enabled', 'healthy', 'id', 'lastHeartbeatAt', 'maxAccounts', 'name', 'updatedAt'] as const
  $columns = ServiceNodeSchema.$columns
  @column()
  declare allocationOrder: number
  @column()
  declare baseUrl: string
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column()
  declare healthy: boolean
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastHeartbeatAt: DateTime | null
  @column()
  declare maxAccounts: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
