import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('service_nodes', (table) => {
      table.increments('id').primary()
      table.string('code', 120).notNullable().unique()
      table.string('name', 180).notNullable()
      table.string('base_url', 255).notNullable()
      table.integer('max_accounts').notNullable().defaultTo(3)
      table.boolean('healthy').notNullable().defaultTo(true)
      table.timestamp('last_heartbeat_at', { useTz: true }).nullable()
      table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(this.now())
      table.timestamp('updated_at', { useTz: true }).nullable()
    })

    this.schema.createTable('managed_accounts', (table) => {
      table.increments('id').primary()
      table.string('slug', 160).notNullable().unique()
      table.string('account', 64).notNullable().unique()
      table.string('password', 255).notNullable()
      table.text('token').notNullable().defaultTo('')
      table
        .string('container_code', 120)
        .references('code')
        .inTable('service_nodes')
        .onDelete('SET NULL')
      table.string('status', 48).notNullable().defaultTo('pending')
      table.string('token_status', 48).notNullable().defaultTo('inactive')
      table.string('last_error', 500).nullable()
      table.integer('token_expires_at').nullable()
      table.timestamp('last_synced_at', { useTz: true }).nullable()
      table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(this.now())
      table.timestamp('updated_at', { useTz: true }).nullable()
      table.index(['container_code'])
      table.index(['status'])
    })

    this.schema.createTable('account_snapshots', (table) => {
      table.increments('id').primary()
      table
        .integer('managed_account_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('managed_accounts')
        .onDelete('CASCADE')
        .unique()
      table.decimal('available_balance', 14, 2).notNullable().defaultTo(0)
      table.decimal('today_profit', 14, 2).notNullable().defaultTo(0)
      table.decimal('yesterday_profit', 14, 2).notNullable().defaultTo(0)
      table.decimal('total_profit', 14, 2).notNullable().defaultTo(0)
      table.decimal('total_assets', 14, 2).notNullable().defaultTo(0)
      table.decimal('recharge', 14, 2).notNullable().defaultTo(0)
      table.integer('active_projects').notNullable().defaultTo(0)
      table.boolean('can_checkin').notNullable().defaultTo(false)
      table.jsonb('payload').notNullable().defaultTo('{}')
      table.timestamp('updated_at', { useTz: true }).notNullable().defaultTo(this.now())
    })

    this.schema.createTable('project_snapshots', (table) => {
      table.increments('id').primary()
      table
        .integer('managed_account_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('managed_accounts')
        .onDelete('CASCADE')
      table.integer('remote_order_id').notNullable()
      table.string('order_no', 120).nullable()
      table.string('project_name', 255).notNullable()
      table.decimal('pay_amount', 14, 2).notNullable().defaultTo(0)
      table.decimal('daily_profit', 14, 2).notNullable().defaultTo(0)
      table.decimal('total_income', 14, 2).notNullable().defaultTo(0)
      table.decimal('total_revenue', 14, 2).notNullable().defaultTo(0)
      table.integer('period_days').notNullable().defaultTo(0)
      table.integer('run_status').notNullable().defaultTo(0)
      table.boolean('is_receive').notNullable().defaultTo(false)
      table.integer('extra_flag').notNullable().defaultTo(0)
      table.integer('end_time').notNullable().defaultTo(0)
      table.integer('receive_time').nullable()
      table.text('icon_url').nullable()
      table.text('description_html').nullable()
      table.jsonb('payload').notNullable().defaultTo('{}')
      table.timestamp('updated_at', { useTz: true }).notNullable().defaultTo(this.now())
      table.unique(['managed_account_id', 'remote_order_id'])
    })

    this.schema.createTable('checkin_snapshots', (table) => {
      table.increments('id').primary()
      table
        .integer('managed_account_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('managed_accounts')
        .onDelete('CASCADE')
        .unique()
      table.integer('continue_days').notNullable().defaultTo(0)
      table.decimal('total_revenue', 14, 2).notNullable().defaultTo(0)
      table.integer('current_day').nullable()
      table.integer('today_flag').nullable()
      table.boolean('can_checkin').notNullable().defaultTo(false)
      table.jsonb('calendar').notNullable().defaultTo('[]')
      table.jsonb('rewards').notNullable().defaultTo('[]')
      table.jsonb('payload').notNullable().defaultTo('{}')
      table.timestamp('updated_at', { useTz: true }).notNullable().defaultTo(this.now())
    })

    this.schema.createTable('notifications', (table) => {
      table.bigIncrements('id').primary()
      table.string('level', 24).notNullable()
      table.string('scope', 48).notNullable()
      table.string('title', 160).notNullable()
      table.text('message').notNullable()
      table.string('account_slug', 160).nullable()
      table.jsonb('meta').notNullable().defaultTo('{}')
      table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(this.now())
      table.index(['account_slug'])
      table.index(['created_at'])
    })
  }

  async down() {
    this.schema.dropTable('notifications')
    this.schema.dropTable('checkin_snapshots')
    this.schema.dropTable('project_snapshots')
    this.schema.dropTable('account_snapshots')
    this.schema.dropTable('managed_accounts')
    this.schema.dropTable('service_nodes')
  }
}
